# Generated by Django 2.1.11 on 2019-08-01 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content1', models.CharField(max_length=200)),
                ('content2', models.CharField(max_length=200)),
                ('content3', models.CharField(max_length=200)),
                ('content4', models.CharField(max_length=200)),
                ('content5', models.CharField(max_length=200)),
                ('content6', models.CharField(max_length=200)),
                ('content7', models.CharField(max_length=200)),
                ('content8', models.CharField(max_length=200)),
                ('content9', models.CharField(max_length=200)),
                ('content10', models.CharField(max_length=200)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CareerMatrix.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='detail',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CareerMatrix.Role'),
        ),
        migrations.AddField(
            model_name='detail',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CareerMatrix.Year'),
        ),
    ]
