# Generated by Django 2.1.11 on 2019-08-01 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CareerMatrix', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='billable_hours',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
