# Generated by Django 2.1.11 on 2019-08-01 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CareerMatrix', '0002_detail_billable_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='billable_hours',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='detail',
            name='content1',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='detail',
            name='content10',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='detail',
            name='content2',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='detail',
            name='content3',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='detail',
            name='content4',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='detail',
            name='content5',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='detail',
            name='content6',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='detail',
            name='content7',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='detail',
            name='content8',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='detail',
            name='content9',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
