# Generated by Django 2.1.11 on 2019-08-01 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CareerMatrix', '0004_auto_20190801_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='content21',
            field=models.TextField(blank=True, default=''),
        ),
    ]
