# Generated by Django 2.1.11 on 2019-08-01 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CareerMatrix', '0006_auto_20190801_1527'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detail',
            old_name='content1',
            new_name='general_content',
        ),
        migrations.RenameField(
            model_name='detail',
            old_name='content2',
            new_name='year1_content',
        ),
        migrations.RenameField(
            model_name='detail',
            old_name='header1',
            new_name='year1_header',
        ),
        migrations.RenameField(
            model_name='detail',
            old_name='content3',
            new_name='year2_content',
        ),
        migrations.RenameField(
            model_name='detail',
            old_name='header2',
            new_name='year2_header',
        ),
        migrations.RenameField(
            model_name='detail',
            old_name='header3',
            new_name='year3_header',
        ),
        migrations.AddField(
            model_name='detail',
            name='year3_content',
            field=models.TextField(blank=True, default=''),
        ),
    ]
