# Generated by Django 2.1.11 on 2019-08-01 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CareerMatrix', '0007_auto_20190801_1542'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detail',
            old_name='year1_content',
            new_name='year_content_first_section',
        ),
        migrations.RenameField(
            model_name='detail',
            old_name='year2_content',
            new_name='year_content_second_section',
        ),
        migrations.RenameField(
            model_name='detail',
            old_name='year3_content',
            new_name='year_content_third_section',
        ),
        migrations.RenameField(
            model_name='detail',
            old_name='year1_header',
            new_name='year_header_first_section',
        ),
        migrations.RenameField(
            model_name='detail',
            old_name='year2_header',
            new_name='year_header_second_section',
        ),
        migrations.RenameField(
            model_name='detail',
            old_name='year3_header',
            new_name='year_header_third_section',
        ),
    ]
