# Generated by Django 2.1.11 on 2019-08-01 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CareerMatrix', '0008_auto_20190801_1545'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detail',
            old_name='year_content_first_section',
            new_name='sub_content_first_section',
        ),
        migrations.RenameField(
            model_name='detail',
            old_name='year_content_second_section',
            new_name='sub_content_second_section',
        ),
        migrations.RenameField(
            model_name='detail',
            old_name='year_content_third_section',
            new_name='sub_content_third_section',
        ),
        migrations.RenameField(
            model_name='detail',
            old_name='year_header_first_section',
            new_name='sub_header_first_section',
        ),
        migrations.RenameField(
            model_name='detail',
            old_name='year_header_second_section',
            new_name='sub_header_second_section',
        ),
        migrations.RenameField(
            model_name='detail',
            old_name='year_header_third_section',
            new_name='sub_header_third_section',
        ),
    ]
